import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8').replace(/\r/g,'');
const admin=read('InferenceNode/static/js/admin-users.js'),tel=read('InferenceNode/templates/telemetry.html'),media=read('InferenceNode/templates/media.html');
function fn(src,name){let a=src.indexOf(`function ${name}(`);if(src.slice(a-6,a)==='async ')a-=6;return src.slice(a,src.indexOf('\n}\n',a)+3)}
test('user listing ignores earlier response',async()=>{const pending=[];const ctx=vm.createContext({usersSequence:0,apiCall:()=>new Promise(r=>pending.push(r)),renderStats(){},renderUsers(){}});vm.runInContext(fn(admin,'loadUsers'),ctx);const a=ctx.loadUsers({showSkeleton:false}),b=ctx.loadUsers({showSkeleton:false});pending[1]({ok:true,data:{users:[{id:2}]}});await b;pending[0]({ok:true,data:{users:[{id:1}]}});await a;assert.equal(ctx.allUsers[0].id,2);});
test('old access load cannot populate a newer user modal',async()=>{const pending=[];const fields={};for(const id of ['ac-username','ac-admin-note','ac-body','ac-search'])fields[id]={querySelectorAll:()=>[]};const ctx=vm.createContext({usersWritePending:false,accessSequence:0,document:{getElementById:id=>fields[id]},modals:{access:{show(){}}},apiCall:()=>new Promise(r=>pending.push(r)),accessRowHtml:(p,g)=>g.marker});vm.runInContext(fn(admin,'openPipelineAccess'),ctx);const a=ctx.openPipelineAccess({id:1,username:'First',role:'user'}),b=ctx.openPipelineAccess({id:2,username:'Second',role:'user'});pending[2]({ok:true,data:{pipelines:[{pipeline_id:'p'}]}});pending[3]({ok:true,data:{access:[{pipeline_id:'p',marker:'second'}]}});await b;pending[0]({ok:true,data:{pipelines:[{pipeline_id:'p'}]}});pending[1]({ok:true,data:{access:[{pipeline_id:'p',marker:'first'}]}});await a;assert.equal(fields['ac-username'].textContent,'Second');assert.ok(fields['ac-body'].innerHTML.includes('second'));assert.ok(!fields['ac-body'].innerHTML.includes('first'));});
test('admin mutation guard blocks duplicate writes',async()=>{let resolve,calls=0;const controls=[{disabled:false}];const ctx=vm.createContext({usersWritePending:false,usersSequence:0,document:{querySelectorAll:()=>controls},setButtonLoading(){},apiCall:()=>{calls++;return new Promise(r=>resolve=r)}});vm.runInContext(fn(admin,'write'),ctx);const a=ctx.write('/user','PATCH',{});assert.equal((await ctx.write('/user','PATCH',{})).ok,false);assert.equal(calls,1);assert.equal(controls[0].disabled,true);resolve({ok:true});await a;assert.equal(controls[0].disabled,false);});
test('telemetry poll cannot overlap and missing samples remain gaps',async()=>{let resolve,calls=0;const samples=[];const ctx=vm.createContext({telemetryPollPending:false,fetch:()=>{calls++;return new Promise(r=>resolve=r)},updateCharts:m=>samples.push(m.cpu),document:{getElementById:()=>null}});vm.runInContext(fn(tel,'fetchTelemetryData')+fn(tel,'updateChart'),ctx);const a=ctx.fetchTelemetryData();await ctx.fetchTelemetryData();assert.equal(calls,1);resolve({ok:true,json:async()=>({metrics:{cpu:2}})});await a;assert.deepEqual(samples,[2]);const chart={data:{datasets:[{data:[]}]},update(){}};ctx.updateChart(chart,null);assert.deepEqual(chart.data.datasets[0].data,[null]);});
test('late telemetry configuration does not overwrite a dirty draft',async()=>{let resolve;const field={value:'typed'};const ctx=vm.createContext({telemetryDraftVersion:0,telemetrySavePending:false,fetch:()=>new Promise(r=>resolve=r),document:{getElementById:()=>field},telemetryAlert(){}});vm.runInContext(fn(tel,'loadTelemetryConfig'),ctx);const a=ctx.loadTelemetryConfig();ctx.telemetryDraftVersion++;resolve({ok:true,json:async()=>({mqtt_server:'old'})});await a;assert.equal(field.value,'typed');});
test('media list ignores stale refresh',async()=>{const pending=[];const fields={mediaList:{setAttribute(){}},mediaSummary:{},mediaUpdated:{}};const ctx=vm.createContext({mediaSequence:0,renderMedia(){},fetchJSON:()=>new Promise(r=>pending.push(r)),document:{getElementById:id=>fields[id]},fmtSize:()=>'',mediaStatusBadge:()=>'',refsCell:()=>'',esc:String});vm.runInContext(fn(media,'loadMedia'),ctx);const a=ctx.loadMedia(),b=ctx.loadMedia();pending[1]({ok:true,json:async()=>({media:[{media_id:'new',relative_path:'new'}],count:1})});await b;pending[0]({ok:true,json:async()=>({media:[],count:0})});await a;assert.equal(ctx.mediaCache[0].media_id,'new');});
test('media cannot switch selected deletion while request is pending',()=>{const ctx=vm.createContext({mediaDeleting:true,pendingDelete:'first'});vm.runInContext(fn(media,'askDeleteMedia'),ctx);ctx.askDeleteMedia('second');assert.equal(ctx.pendingDelete,'first');assert.ok(media.includes("showAlert('success', esc("));});
