import fs from 'node:fs';import vm from 'node:vm';import test from 'node:test';import assert from 'node:assert/strict';
const source=fs.readFileSync(new URL('../InferenceNode/templates/publisher.html',import.meta.url),'utf8').replace(/\r/g,'');
const helpers=source.slice(source.indexOf('let publisherPending'),source.indexOf('// Filter function'));
function fn(name){let a=source.indexOf(`function ${name}(`);if(source.slice(a-6,a)==='async ')a-=6;return source.slice(a,source.indexOf('\n}\n',a)+3)}
function handler(id){const a=source.indexOf(`document.getElementById('${id}').addEventListener('submit', async function(e) {`);return source.slice(a,source.indexOf('\n});',a)+4)}
function setup(extra={}) {
 const fields={destinationType:{value:'null'},favoriteName:{value:'<b>name</b>'},favoriteDescription:{value:''},destinationForm:{dataset:{},reset(){}},cancelEditBtn:{style:{}}};const alerts=[];const controls=[{disabled:false},{disabled:true}];
 const ctx=vm.createContext({document:{getElementById:id=>fields[id],querySelector:()=>({}),querySelectorAll:()=>controls},esc:s=>String(s).replaceAll('<','&lt;').replaceAll('>','&gt;'),showAlert:(...a)=>alerts.push(a),console,...extra});vm.runInContext(helpers,ctx);return {ctx,fields,controls,alerts};
}
test('one operation locks fields and restores disabled states',()=>{const {ctx,controls}=setup();assert.equal(ctx.beginPublisherOperation(),true);assert.equal(ctx.beginPublisherOperation(),false);assert.ok(controls.every(c=>c.disabled));ctx.endPublisherOperation();assert.deepEqual(controls.map(c=>c.disabled),[false,true]);});
test('older favorite GET cannot overwrite newer data',async()=>{const pending=[];const {ctx}=setup({fetch:()=>new Promise(r=>pending.push(r)),updateFavoritesList(){}});vm.runInContext(fn('loadFavoriteConfigs'),ctx);const a=ctx.loadFavoriteConfigs(),b=ctx.loadFavoriteConfigs();pending[1]({ok:true,json:async()=>({favorites:[{id:'new'}]})});await b;pending[0]({ok:true,json:async()=>({favorites:[{id:'old'}]})});await a;assert.equal(ctx.favoriteConfigs[0].id,'new');});
test('failed GET displays an error',async()=>{const {ctx,alerts}=setup({fetch:async()=>({ok:false})});vm.runInContext(fn('loadFavoriteConfigs'),ctx);await ctx.loadFavoriteConfigs();assert.equal(alerts[0][0],'error');});
test('notifications escape favorite markup',()=>{const {ctx,alerts}=setup();ctx.publisherAlert('success','<b>name</b>');assert.equal(alerts[0][1],'&lt;b&gt;name&lt;/b&gt;');});
test('save suppresses repeat submits and releases controls after failure',async()=>{let submit,resolve,calls=0;const {ctx,fields,controls}=setup({collectConfigFromSchema:()=>({isValid:true,config:{}}),fetch:()=>{calls++;return new Promise(r=>resolve=r)},loadFavoriteConfigs(){},updateConfigForm(){}});fields.destinationForm.addEventListener=(e,f)=>submit=f;vm.runInContext(handler('destinationForm'),ctx);const a=submit.call(fields.destinationForm,{preventDefault(){}});await submit.call(fields.destinationForm,{preventDefault(){}});assert.equal(calls,1);assert.ok(controls.every(c=>c.disabled));resolve({ok:false,json:async()=>({error:'write failed'})});await a;assert.equal(controls[0].disabled,false);assert.equal(fields.favoriteName.value,'<b>name</b>');});
test('editing is synchronous and Cancel has no pending callback to restore data',()=>{let populated=0;const {ctx,fields}=setup({availableDestinationTypes:[{type:'null',available:true}],favoriteConfigs:[{id:'one',name:'One',type:'null',config:{}}],selectDestinationType(){},populateConfigForm(){populated++},updateConfigForm(){},setTimeout(){assert.fail('Edit must not use a delayed callback')}});vm.runInContext(fn('useFavoriteConfig')+fn('cancelEdit'),ctx);ctx.useFavoriteConfig('one');assert.equal(populated,1);ctx.cancelEdit();assert.equal(fields.destinationForm.dataset.editingId,undefined);assert.equal(fields.cancelEditBtn.style.display,'none');});
test('test handler sends pipeline context, guards repeat clicks and counts per-result outcomes',async()=>{let submit,resolve,calls=0,payload;const {ctx,fields}=setup({publishStats:{total:0,errors:0},fetch:(url,opt)=>{calls++;payload=JSON.parse(opt.body);return new Promise(r=>resolve=r)}});fields.testPublishForm={addEventListener:(e,f)=>submit=f};fields.testMessage={value:'{"test":true}'};fields.testPipeline={value:'pipeline-one'};fields.totalPublished={};fields.publishErrors={};const original=ctx.document.querySelectorAll;ctx.document.querySelectorAll=s=>s.includes(':checked')?[{value:'favorite'}]:original(s);vm.runInContext(handler('testPublishForm'),ctx);const a=submit({preventDefault(){}});await submit({preventDefault(){}});assert.equal(calls,1);assert.equal(payload.pipeline_id,'pipeline-one');resolve({ok:false,json:async()=>({status:'error',message:'partial failure',results:{a:{status:'success'},b:{status:'error'}}})});await a;assert.equal(fields.totalPublished.textContent,1);assert.equal(fields.publishErrors.textContent,1);});
